version: '3.4'

services:
  weatherapi:
    container_name: demo-weatherapi
    image: registry/org/weatherapi
    build:
      context: .
      dockerfile: DemoWebApi/Dockerfile
    ports:
      - '5015:80'
      - '7015:443'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80